"""initial commerce schema

Revision ID: 0001
Revises:
Create Date: 2025-01-06

Hand-written rather than autogenerated. Autogenerate does not emit partial
indexes, column comments, or the CHECK constraints that encode the domain
rules, and those are the parts of this schema that matter.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "customers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("timezone", sa.Text(), nullable=False, server_default="UTC"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("email", name="uq_customers_email"),
        sa.CheckConstraint("char_length(country_code) = 2", name="ck_customers_country_len"),
        sa.CheckConstraint("position('@' in email) > 1", name="ck_customers_email_shape"),
    )
    op.create_index("ix_customers_created_at", "customers", ["created_at"])
    op.create_index("ix_customers_updated_at", "customers", ["updated_at"])
    op.create_index(
        "ix_customers_active", "customers", ["id"], postgresql_where=sa.text("deleted_at IS NULL")
    )

    op.create_table(
        "plans",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("monthly_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD"),
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("code", name="uq_plans_code"),
        sa.CheckConstraint("monthly_cents >= 0", name="ck_plans_monthly_cents_nonneg"),
    )

    op.create_table(
        "subscriptions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("customer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], name="fk_subscriptions_customer"),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], name="fk_subscriptions_plan"),
        sa.CheckConstraint(
            "ended_at IS NULL OR ended_at >= started_at", name="ck_subscriptions_period_ordered"
        ),
    )
    op.create_index("ix_subscriptions_customer_id", "subscriptions", ["customer_id"])
    op.create_index("ix_subscriptions_updated_at", "subscriptions", ["updated_at"])
    op.create_index("ix_subscriptions_status", "subscriptions", ["status"])

    op.create_table(
        "subscription_events",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("subscription_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("from_plan_id", sa.Integer(), nullable=True),
        sa.Column("to_plan_id", sa.Integer(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], name="fk_sub_events_subscription"),
        sa.ForeignKeyConstraint(["from_plan_id"], ["plans.id"], name="fk_sub_events_from_plan"),
        sa.ForeignKeyConstraint(["to_plan_id"], ["plans.id"], name="fk_sub_events_to_plan"),
    )
    op.create_index("ix_sub_events_subscription_id", "subscription_events", ["subscription_id"])
    op.create_index("ix_sub_events_occurred_at", "subscription_events", ["occurred_at"])
    op.create_index("ix_sub_events_created_at", "subscription_events", ["created_at"])

    op.create_table(
        "orders",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("customer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("subscription_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        # Nullable on purpose. See models.py, point 1.
        sa.Column("placed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "placed_at_local",
            sa.Text(),
            nullable=True,
            comment="Naive local wall-clock from the legacy mobile client, "
            "'YYYY-MM-DD HH:MM:SS', no offset. Resolve against customers.timezone.",
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], name="fk_orders_customer"),
        sa.ForeignKeyConstraint(["subscription_id"], ["subscriptions.id"], name="fk_orders_subscription"),
        sa.CheckConstraint("amount_cents >= 0", name="ck_orders_amount_nonneg"),
        sa.CheckConstraint(
            "placed_at IS NOT NULL OR placed_at_local IS NOT NULL",
            name="ck_orders_placed_at_present",
        ),
    )
    op.create_index("ix_orders_customer_id", "orders", ["customer_id"])
    op.create_index("ix_orders_placed_at", "orders", ["placed_at"])
    op.create_index("ix_orders_updated_at", "orders", ["updated_at"])
    op.create_index("ix_orders_status", "orders", ["status"])

    op.create_table(
        "payments",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("order_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("method", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], name="fk_payments_order"),
        sa.CheckConstraint("amount_cents >= 0", name="ck_payments_amount_nonneg"),
        sa.CheckConstraint(
            "status <> 'succeeded' OR processed_at IS NOT NULL",
            name="ck_payments_succeeded_has_processed_at",
        ),
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"])
    op.create_index("ix_payments_updated_at", "payments", ["updated_at"])
    op.create_index("ix_payments_processed_at", "payments", ["processed_at"])

    op.create_table(
        "refunds",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("payment_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["payment_id"], ["payments.id"], name="fk_refunds_payment"),
        sa.CheckConstraint("amount_cents > 0", name="ck_refunds_amount_positive"),
    )
    op.create_index("ix_refunds_payment_id", "refunds", ["payment_id"])
    op.create_index("ix_refunds_issued_at", "refunds", ["issued_at"])
    op.create_index("ix_refunds_created_at", "refunds", ["created_at"])

    op.create_table(
        "idempotency_keys",
        sa.Column("key", sa.Text(), primary_key=True),
        sa.Column("endpoint", sa.Text(), primary_key=True),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_status", sa.Integer(), nullable=False),
        sa.Column("response_body", postgresql.JSONB(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
    )
    op.create_index("ix_idempotency_created_at", "idempotency_keys", ["created_at"])

    # REPLICA IDENTITY FULL on the tables the warehouse needs to see deletes
    # and before-images for. Without it a DELETE arrives from Debezium with
    # only the primary key populated, and an UPDATE carries no `before` state,
    # which makes it impossible to tell a soft delete from a hard one
    # downstream. It costs WAL volume; that trade is documented in DESIGN.md.
    for table in ("customers", "subscriptions", "orders", "payments", "refunds"):
        op.execute(f"ALTER TABLE {table} REPLICA IDENTITY FULL")


def downgrade() -> None:
    op.drop_table("idempotency_keys")
    op.drop_table("refunds")
    op.drop_table("payments")
    op.drop_table("orders")
    op.drop_table("subscription_events")
    op.drop_table("subscriptions")
    op.drop_table("plans")
    op.drop_table("customers")
